-- MySQL Script generated by MySQL Workbench
-- Wed 25 Nov 2015 11:52:42 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema susi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema susi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `susi` DEFAULT CHARACTER SET utf8 ;
USE `susi` ;

-- -----------------------------------------------------
-- Table `susi`.`item_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `susi`.`item_types` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `susi`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `susi`.`items` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL,
  `item_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_items_item_types_idx` (`item_type_id` ASC),
  CONSTRAINT `fk_items_item_types`
    FOREIGN KEY (`item_type_id`)
    REFERENCES `susi`.`item_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `susi`.`campuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `susi`.`campuses` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `susi`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `susi`.`user_types` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `susi`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `susi`.`users` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  `user_type_id` INT UNSIGNED NOT NULL,
  `campus_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_types_idx` (`user_type_id` ASC),
  INDEX `fk_users_campuses_idx` (`campus_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  CONSTRAINT `fk_users_user_types`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `susi`.`user_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_campuses`
    FOREIGN KEY (`campus_id`)
    REFERENCES `susi`.`campuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `susi`.`utilizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `susi`.`utilizations` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `susi`.`item_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `susi`.`item_details` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `susi`.`campus_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `susi`.`campus_items` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `lot` INT NOT NULL,
  `validity` DATE NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `item_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NULL,
  `utilization_id` INT UNSIGNED NULL,
  `item_detail_id` INT UNSIGNED NULL,
  INDEX `fk_campus_items_users_idx` (`user_id` ASC),
  INDEX `fk_campus_items_user_types_idx` (`utilization_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_campus_items_item_details_idx` (`item_detail_id` ASC),
  INDEX `fk_campus_items_items_idx` (`item_id` ASC),
  CONSTRAINT `fk_campus_items_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `susi`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campus_items_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `susi`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campus_items_utilizations`
    FOREIGN KEY (`utilization_id`)
    REFERENCES `susi`.`utilizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campus_items_item_details`
    FOREIGN KEY (`item_detail_id`)
    REFERENCES `susi`.`item_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
